### ISSUE TITLE
Unable to run the shell script in python 3.10

### ISSUE THREAD

**Issue by Deepa-Santhosh** [kpol-iisc/PYTSN#1]
Hi,

I am trying to run the experiments mentioned in PYTSN-v2. 
As mentioned in the GitHub readme file, the software prerequisites are **python==2.7, simpy==3.0.13, pandas==0.24.2, matplotlib==2.2.3** 
I am using **Ubuntu 22.04 LTS**
Below are the packages installed:
**python==3.10, simpy==4.1.0, pandas==2.0.3, matplotlib==3.7.1**

While executing run.py file I am getting the following error message:

**Traceback (most recent call last):
  File "/home/student/Desktop/PYTSN/PYTSN-v2/run.py", line 5, in <module>
    from modules.traffic import const, poisson
ImportError: bad magic number in 'modules': b'\x03\xf3\r\n'**

Is this error rising due to version issue? 
Can I run the experiment with the above mentioned packages version? Or do I need to use the packages as per the version mentioned in the GitHub docs?

Any help would be highly appreciated.
Thank you.

**Comment by dr-polachan** [comment]
The scripts won’t work on Python v3

**Comment by Deepa-Santhosh** [comment]
Ok Sir. Thank you for the confirmation.
